version: "3.9"
services:
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9090" /data/
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: user123
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio-storage:/data