# Use postgres/example user/password credentials
version: '3.1'

volumes:
  postgres_data:

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
  
  #pgadmin:
  #  image: dpage/pgadmin4
  #  restart: always
  #  ports:
  #    - 15432:80
  #  environment:
  #    - PGADMIN_DEFAULT_PASSWORD=password
  #    - PGADMIN_DEFAULT_EMAIL=example@mail.com